### ISSUE TITLE
Some hard constraints don't seem to be adhered to

### ISSUE THREAD

**Issue by kapil1garg** [NUDelta/dtr-group-maker#2]
When entering hard constraints with overlaps in the Pair Research Pairings section, some of the constraints are not being upheld after the partitioning algorithm runs. For instance, in the example below the added hard constraints in blue somehow override the pair research pairing constraints, which results in some pairs--like Sanfeng and Ryan L--being in separate partitions. 

![Screen Shot 2019-05-04 at 2 13 03 AM](https://user-images.githubusercontent.com/3069370/57175592-80738880-6e13-11e9-8f54-e8ed49c0bdfe.png)

Labeling as a possible bug right now, but will need to investigate to make sure.

**Comment by haoqizhang** [comment]
The user is adding a "triple" preference (Josh,Caryl,Cooper) when the pair research hard constraints expect only pairwise constraints. Given the current implementation, the user can instead enter [Josh, Caryl], [Caryl, Cooper], and [Josh, Cooper] separately -- that yields the current, expected results.

The issue is that computeGoodHardPartitions checks only the length of the preference list to see how many paired constraints were respected in the final matching. I will commit a version of the code now that abstracts this to a numPrefs function, so in future implementations we can compute how many preferences there actually are in a listing, since (Josh,Caryl,Cooper) is really 3 preferences. Not doing this quick fix now because of 2 outstanding issues:

1) We would need to properly account for duplicates  (e.g., Josh and Cooper get paired for pair research and also need to work on LIPs together -- make sure this checks out with the computeScore function)

2) Cases where it is not possible to respect the full set of hard constraints including non-pair-research constraints as hard constraints, since that would lead to uneven partitions. In other words, keeping people together for reasons that are not pair research should not be hard constraints, period. If they need to be hard constraints and pair research constraints are hard constraints, you can easily have infeasible solutions because these may naturally conflict --- given that the pairings for pair research are made without consideration of these other LIP pairing constraints.

**Comment by haoqizhang** [comment]
argh, i got soft and added support for adding triples as hard constraints too (e.g., josh/Caryl/Cooper). I still consider this a bit of a hack and the wrong usage pattern, but practically we do do this. I pushed to master.... this should work for now.
